### ISSUE TITLE
Labels and milestones

### ISSUE THREAD

**Issue by sofer** [MindAidPrototype/MindAidUser#7]
Here's some small suggestions. Turn all your your user stories into issues. Label your issues. Create some labels for time estimates, too. Create a couple of milestones (Friday could be the first one). Prioritise your issues by adding them to the first milestone. See https://github.com/dwyl/dwyl.github.io/issues for a good example of use of labels and https://github.com/SimonLab/user-story-checklist for guidance on issue workflow.

**Comment by shouston3** [comment]
Have only just addressed our issues on this page today, labels have been made and added labels to them
